### ISSUE TITLE
Namespace is hard-coded in some files

### ISSUE THREAD

**Issue by somdoron** [funkypenguin/helm-kubernetes-dashboard#1]
I failed to install the chart, getting an error "namespaced kubernetes-dashboard not found". 
I checked the files and it seems in some places the namespace is hardcoded:

https://github.com/funkypenguin/helm-kubernetes-dashboard/blob/a1b2eede0bd4562c8ddec983b1d717fef9b88489/helm-chart/kubernetes-dashboard/templates/deployment.yaml#L132

https://github.com/funkypenguin/helm-kubernetes-dashboard/blob/2a72cd93a1ce51ee84bca2c9efd99973a9a55390/helm-chart/kubernetes-dashboard/templates/svc.yaml#L48

**Comment by funkypenguin** [comment]
I'm not sure what the best practice here is re specifying namespaces in a chart... we _need_ namespaces for RBAC though, so I've gone with the parametized version instead of the hard-coded one, in the examples above.

Thanks again! :)
D
