### ISSUE TITLE
Inconsistent name for secret

### ISSUE THREAD

**Issue by somdoron** [funkypenguin/helm-kubernetes-dashboard#2]
The name of what suppose to be the same is different.

https://github.com/funkypenguin/helm-kubernetes-dashboard/blob/master/helm-chart/kubernetes-dashboard/templates/deployment.yaml#L113

https://github.com/funkypenguin/helm-kubernetes-dashboard/blob/master/helm-chart/kubernetes-dashboard/templates/secret.yaml#L9

**Comment by funkypenguin** [comment]
Fixed, thanks @somdoron for pointing that out! :)
