### ISSUE TITLE
hardcodings for namespace and chart name

### ISSUE THREAD

**Issue by ReSearchITEng** [funkypenguin/helm-kubernetes-dashboard#3]
First of all, thanks for this chart! Is/will it be submitted to the official locations ?

In current form, it works only only if both namespace and the release name are exactly:  "kubernetes-dashboard"

**Comment by funkypenguin** [comment]
It's in the process of supporting an "official location", at https://github.com/kubernetes/dashboard/pull/4502 ;)

**Comment by ReSearchITEng** [comment]
Just noticed that the version in here (github) does not seem to have this hardcoding issue.  I am closing it.
Btw, are you on slack?

**Comment by funkypenguin** [comment]
Best way to contact me is in http://chat.funkypenguin.co.nz - I'm "Darth Penguini" at the moment ;)

**Comment by ReSearchITEng** [comment]
I noticed in few places there is "namespace: {{ .Release.Namespace }}"
are those required?

**Comment by funkypenguin** [comment]
Sorry, I dropped the ball here! I'm deprecating this chart in favor of https://github.com/kubernetes/dashboard/tree/master/aio/deploy/helm-chart/kubernetes-dashboard (which is partly based on mine)
